spring.datasource.url=jdbc:postgresql://localhost:5432/joblync
spring.datasource.username=postgres
spring.datasource.password=Password
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

jwt.secret=ZmFrZVNlY3JldEtleUhlcmVXaXRoU3VwZXJTdHJvbmdFbmNyeXB0aW9uIQ==
logging.level.org.hibernate.SQL=DEBUG


app-admin.admin.email=super@joblync.com
app-admin.admin.password=secret
app-admin.admin.level=SUPER_ADMIN

app-admin.subadmin.email=sub@joblync.com
app-admin.subadmin.password=subsecret
app-admin.subadmin.level=SUB_ADMIN


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



