spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Password
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

jwt.secret=ZmFrZVNlY3JldEtleUhlcmVXaXRoU3VwZXJTdHJvbmdFbmNyeXB0aW9uIQ==
logging.level.org.springframework.security=DEBUG

app-admin.admin.email=super@joblync.com
app-admin.admin.password=secret
app-admin.admin.level=SUPER_ADMIN

app-admin.subadmin.email=sub@joblync.com
app-admin.subadmin.password=subsecret
app-admin.subadmin.level=SUB_ADMIN


